### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by TitanNet** [TitanNet/Allocator-Pathway-Titan-Network#1]
### Version

1

### DataCap Applicant

titantest

### Project ID

1

### Data Owner Name

titantest

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

titantest.com

### Social Media Handle

titantest

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

1

### Unit for total amount of DataCap being requested

GiB

### Expected size of single dataset (one copy)

2

### Unit for expected size of single dataset

GiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

1

### Unit for weekly allocation of DataCap requested

GiB

### On-chain address for first allocation

titantest

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
titantest
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
titantest
```

### Describe the data being stored onto Filecoin

```text
titantest
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you answered "Other" in the previous question, enter the details here

```text
titantest
```

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
titantest
```

### Please share a sample of the data

```text
titantest
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

North America

### How will you be distributing your data to storage providers

IPFS

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
titantest
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by khazyaen** [comment]
Coll
